### ISSUE TITLE
Support for openSUSE (Tumbleweed)

### ISSUE THREAD

**Issue by SecUpwN** [ruped24/toriptables2#1] opened 2016-02-26 13:22 UTC
Good evening @ruped24, thanks for developing your neat script here! I am already running [torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher) by @micahflee which sadly lacks the functionality of anonymizing all traffic. Now I would like to do just that on my Laptop running [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed), but once I load your script I get the following error before all internet connections stop working (likely because the owner `debian-tor` does not exist):

```
SecUpwN@GLaDOS:~> sudo python /home/SecUpwN/Schreibtisch/toriptables2.py -l
root's password:
iptables v1.6.0: owner: Bad value for "--uid-owner" option: "id: „debian-tor“: Einen solchen Benutzer gibt es nicht"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.0: owner: Bad value for "--uid-owner" option: "id: „debian-tor“: Einen solchen Benutzer gibt es nicht"
Try `iptables -h' or 'iptables --help' for more information.
[!] Command failed: ['service', 'tor', 'restart']
```

**Comment by ruped24** [comment] 2016-02-26 14:07
Error 1: iptables v1.6.0: owner: Bad value for "--uid-owner"

[1]  It's looking for debian base distro's  tor user.  Look in /etc/group for the tor user name
Try this Fix: Replace debian-tor with suse tor user name
Line 29:  self.tor_uid = getoutput("id -ur debian-tor")

Error 2: [!] Command failed: ['service', 'tor', 'restart']

[2] Suse is using systemctl, were as debian uses service
Try this fixes:
Line 54:   tor_restart = check_call(["service", "tor", "restart"],
Replace with:
Line 54: tor_restart = check_call(["systemctl", "start", "tor.service"],

Note: I don't have a Suse box handy to test it.  Let me know if you are still having problems.

**Comment by SecUpwN** [comment] 2016-02-27 06:30
>Look in your /etc/group file for the ***tor*** user name.

Thanks for your help, but there currently is none. Have a [look](https://defuse.ca/b/ncF0t8zo).

>Line 54: tor_restart = check_call(["service", "tor", "restart"],
>Replace with:
>**Line 54: tor_restart = check_call(["systemctl", "start", "tor.service"]**

I've added the second fix and will wait for your reply on your answer on the first.
Are you going to update your script after I've confirmed that these fixes work?

**Comment by ruped24** [comment] 2016-02-27 12:18
I don't see a tor user.

1.  *Is tor installed*?  Or look in /etc/password
2. It probably uses the name *tor*, and NOT debian-tor
3. The script was written for pentesting distros (kali linux).  Witch most
are Debian base (apt-get).
4.  If I were to add other distros (I tried), it will require checking eg.
sysV or systemd and tor user id ... The user id is the tough one, not the
former.


Once you get it working.  I can post a how to for rpm based distros.
If it's simple enough, I can do #4.  The tricky part is getting the tor
user id right (every time) on all distro.

Let see what the fix looks like, then I can write a patch for you and a
script to patch it.

Your main problem now is finding the tor user name.  I don't have a Suse
box i can spin up right now.  Time is my enemy :(

Let me know you findings ...

Thx, ttyl

On Sat, Feb 27, 2016 at 1:31 AM, Security: PWNED <notifications@github.com>
wrote:

> Look in your /etc/group file for the *tor* user name.
>
> Thanks for your help, but there currently is none. Have a look
> <https://defuse.ca/b/ncF0t8zo>.
>
> Line 54: tor_restart = check_call(["service", "tor", "restart"],
> Replace with:
> *Line 54: tor_restart = check_call(["systemctl", "start", "tor.service"]*
>
> I've added the second fix and will wait for your reply on your answer on
> the first.
> Are you going to update your script after I've confirmed that these fixes
> work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruped24/toriptables2/issues/1#issuecomment-189585397>.
>



-- 
*Rupert Edwards*
202-670-1594
http://linuxprotraining.com

--“Tell me and I'll forget; show me and I may remember; involve me and I'll
understand.”--

**Comment by SecUpwN** [comment] 2016-02-27 18:56
@ruped24, please remove my quoted email from your previous post on GitHub. I did send the link to the logfile via E-mail to prevent my linux setup appearing on GitHub. Hope you get the point. :)

> 1. *Is tor installed*? Or look in /etc/passwd

Acually, I am *only* using the [torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher), which was installable via YaST or the terminal command `zypper in torbrowser-launcher`. So there is nothing related to be found in `/etc/passwd` either.

**Comment by ruped24** [comment] 2016-02-27 19:28
1. Got it.
2. You need to install the tor binary from your repo.
3. Then look again

**Comment by SecUpwN** [comment] 2016-02-27 20:06
>1. You need to install the_ official tor binary_ from your repo or tor website.

Did that, worked flawlessly.

>2. Type_ tor_ at the command line. You should get back some stuff ....

Did that, `tor` boostraps and connects as it should.

>3. Then look again ... Or try the default name "tor"

I tried your script again after modifying line 54 to say `tor_restart = check_call(["systemctl", "start", "tor.service"]` and changed `debain-tor` to `tor`, then got this result: `[!] Can't get public ip address!`

**Comment by ruped24** [comment] 2016-02-27 20:49
1. Run the test on check.torproject.org
2. If the node is slow, It may timeout fetching the Ip address.
3. Rerun the script -- It will get a new ip address (node)

**Comment by SecUpwN** [comment] 2016-02-27 21:24
>2. Run the test on check.torproject.org

When running `sudo tor` via command line and checking via the normal browser, the check fails.

>4. Rerun the script -- It will get a new ip address (node).

I did in a separate terminal window while `sudo tor` ran in the other one. Result:


```
[!] Command failed: ['systemctl', 'start', 'tor.service']

**Comment by ruped24** [comment] 2016-02-27 21:28
1. You may need to enable systemctl to allow the service to start.
2. Make sure the systemctl sysntax is correct.  Try it on the command line.
Get it to start from the command first.  Configure systemctl to enable the tor service.

**Comment by SecUpwN** [comment] 2016-02-27 22:00
>1. You may need to enable systemd to allow the service to start.

How to do that?

>2. Make sure the systemctl sysntax is correct. Try it on the command line. Get it to start from the command first. Configure systemctl to enable the tor service to start.

Gosh, even more shit to cope with. Can't you add your awesome work via pull request to `torbrowser-launcher` to solve my freshly opened Issue https://github.com/micahflee/torbrowser-launcher/issues/223? That would be lovely.

**Comment by ruped24** [comment] 2016-02-27 22:02
I'll test it on a redhat box and give you the changes.
Give me a few ...
Hang tight ...

**Comment by SecUpwN** [comment] 2016-02-27 22:07
>Give me a few ...

Don't hurry. I've learned that the best things come to those who are willing to be patient.

**Comment by ruped24** [comment] 2016-02-27 22:09
See my error ... in post above.  You might be OK.
I'll still test it right quick.

**Comment by ruped24** [comment] 2016-02-27 22:53
OK. My findings
1. I'm using a Centos 7 box
2. to start the tor service, it uses the old service command.
**Revert back to _Line 54_ original` service tor restart`  statement.**

I'm have some issuses with it starting on Centos, too lockdown.

**Comment by ruped24** [comment] 2016-02-29 01:34
Did it work?
Can I close this issue?

**Comment by SecUpwN** [comment] 2016-02-29 12:03
>Did it work?

Unfortunately not yet. Both `['systemctl', 'restart', 'tor.service']` nor `tor_restart = check_call(['service', 'tor', 'restart']` did work, I'm still getting the `[!] Can't get public ip address!` message. What else to test?

**Comment by ruped24** [comment] 2016-02-29 12:20
Run the command from the command line to see which on starts the tor service
`service tor restrart`
or
`systemctl restart tor.service
`
Run the iptables command to see if the rules were loaded.

```
iptables -S
iptables -S -t nat
```

**Comment by SecUpwN** [comment] 2016-02-29 21:18
>Run the command from the command line to see which on starts the tor service
>`service tor restrart`

Did that and it seems to have [worked](https://defuse.ca/b/YfgRcfg6).

>Run the iptables command to see if the rules were loaded.
>`iptables -S`
>`iptables -S -t nat`

Done. What do these [outpouts](https://defuse.ca/b/z9ebPNwc) tell you?

**Comment by ruped24** [comment] 2016-02-29 21:22
If the iptables rules are set.  New distros use firewalld.
Look at the second screenshot in the Readme.  It should look like that.

**Comment by SecUpwN** [comment] 2016-02-29 21:35
>If the iptables rules are set. New distros use firewalld.

I am using the bleeding edge version of openSUSE, called `Tumbleweed`. The only output I get is this:
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
```

**Comment by ruped24** [comment] 2016-02-29 22:10
1) Open a python interpreter in the directory were toriptables2.py file located.
```
>>> import toriptables2
>>> a = toriptables2.TorIptables()
>>> a.load_iptables_rules()
```
2) See if the runs are now set ...

**Comment by SecUpwN** [comment] 2016-03-05 19:35
Thanks @ruped24. These commands work, but when loading them I have no internet at all anymore. Aren't you able to add support for openSUSE out of the box or add your script to `torbrowser-launcher`?

**Comment by ruped24** [comment] 2016-03-05 19:54
I peaked at the code.  He is building a rpm package.  I would have to look into it more...  Right now, time is my enemy.  I'll see if it's possible.  Thx for showing me that project.  I didn't know about it.

I initially was targeting pentesting distros, which must if not all are deb base.
I'm not going to say change distro,  but it works on *buntu, mint, etc.  
Give it a try in a VM ...

**Comment by ruped24** [comment] 2016-03-05 19:58
Check bottom of your /etc/torrc for these lines:

## Inserted by toriptables2.py for tor iptables rules set
## Transparently route all traffic thru tor on port 9040
VirtualAddrNetwork 10.0.0.0/10
AutomapHostsOnResolve 1
TransPort 9040
DNSPort 53

**Comment by SecUpwN** [comment] 2016-03-06 13:01
>I initially was targeting pentesting distros, which must if not all are deb base.

Are these tables already included in my favourite privacy distro [Tails](https://tails.boum.org/)? I guess so.

```
## Inserted by toriptables2.py for tor iptables rules set
## Transparently route all traffic thru tor on port 9040
VirtualAddrNetwork 10.0.0.0/10
AutomapHostsOnResolve 1
TransPort 9040
DNSPort 53
```

**Comment by ruped24** [comment] 2016-03-06 13:03
Yes>  Leave the comments.  It screwed up "this" format.

**Comment by SecUpwN** [comment] 2016-03-06 13:06
>Yes. Leave the comments. It screwed up "this" format.

What I would like to essentially accomplish, is to make your script work in the background to *automatically* start up when I boot my computer. When connecting to any network, I'd like it to anonymize all traffic. But I have not yet been able to make your script work as it should. Are you going to make a pull request to `towbrowser-launcher` to add this functionality? :)

**Comment by ruped24** [comment] 2016-03-06 13:13
> Are you going to make a pull request to towbrowser-launcher to add this functionality? :)

I'll look into it.  I can't give you a firm date.

**Comment by SecUpwN** [comment] 2016-03-06 13:45
>Unfortunately, I had a narrow target, just the *buntu or debian.

Can you try to make it work with [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed)

>I'll look into it. I can't give you a firm date.

No problem, take your time.

**Comment by ruped24** [comment] 2016-03-06 13:55
I'll spin your distro and get it to work.  I need some time tho.  Not very long.
If you can point me to a live version of Tumbleweed that I don't have to install,  I can do it quick.

**Comment by SecUpwN** [comment] 2016-03-06 14:07
>I'll spin your distro and get it to work. I need some time tho. Not very long.

Sounds wonderful!

>If you can point me to a live version of Tumbleweed that I don't have to install, I can do it quick.

`Tumbleweed` is just the name for the full rolling release. I guess using [this older live CD](http://download.opensuse.org/distribution/13.1/iso/openSUSE-13.1-KDE-Live-i686.iso) should work.

**Comment by ruped24** [comment] 2016-03-06 14:25
Got the iso, looking at it now.  Hang tight.

**Comment by ruped24** [comment] 2016-03-06 14:44
Got it!.  I'll send you a link to the screenshot and post the changes.

**Comment by SecUpwN** [comment] 2016-03-06 14:47
>Got it!. I'll send you a link to the screenshot and post the changes.

Neat! So will you update your script with auto-detection of openSUSE right away?

**Comment by ruped24** [comment] 2016-03-06 15:02
Here is the screenshot: 
http://bit.ly/1p8FAG9

Here is a pastebin link:
http://pastebin.com/yYvFUFDh

The changes was what I stated before in a previous post.
Tor user name = tor
systemctl restart tor.service

**Comment by SecUpwN** [comment] 2016-03-06 15:08
>Here is the screenshot

Whoo-hooo, I'm excited! :smile_cat: How to make your script launch and connect on bootup so that no traffic is leaking without ever being routed through Tor? I'm secretly hoping you update your script with it.

>Here is a pastebin link
Just as as a security note: Do *not* use Pastebin any more, they censor stuff. Use [PIEBIN](https://defuse.ca/pastebin.htm) instead. ;-)

**Comment by ruped24** [comment] 2016-03-06 15:18
> How to make your script launch and connect on bootup
Put it in `/etc/rc.loca`l
make sure it's in your path. 
`chmod +x mv toriptables2.py /usr/local/bin`
Cool.  It's set to expire in a week.
Thx for the note.

**Comment by SecUpwN** [comment] 2016-03-06 15:36
>Put it in `/etc/rc.local`

Done. Your script has been renamed to `rc.local` and moved to `/etc/`. Hope that is right.

>`chmod +x toriptables2.py && mv toriptables2.py /usr/local/bin`

Done. Will this make sure that no traffic is leaking without being anonymized at startup?

>Cool. It's set to expire in a week.

What is set to expire in a week?

**Comment by ruped24** [comment] 2016-03-06 15:51
That will need to start before networking.  Change the priority.  See Suse wiki.

**Comment by ruped24** [comment] 2016-03-06 15:57
Did the modifications work?

**Comment by SecUpwN** [comment] 2016-03-06 16:07
>That will need to start before networking. Change the priority. See Suse wiki.

I've been searching like crazy on how to set the priority of that moved script. Please hlep me there.

>Did the modifications work?

I tested the modified script right after you posted it and still got this: `[!] Can't get public ip address!`

**Comment by ruped24** [comment] 2016-03-06 16:45
>  tested the modified script right after you posted it and still got this: [!] Can't get public ip address!

Unless they changed something in Tumbleweed (bleeding edge).  Dunno

Try it on the iso you sent me.  See if it work on that.  
If yes, Then, Tumbleweed has changed something.

**Comment by SecUpwN** [comment] 2016-03-06 17:01
>Try it on the iso you sent me. See if it work on that.

I can't download that in the moment.

>If yes, Then, Tumbleweed has changed something.

Where to look exactly? Maybe I'm just loading the script worng? I'm doing this the whole time:

`SecUpwN@GLaDOS:~> sudo python /home/SecUpwN/toriptables2.py -l`

**Comment by ruped24** [comment] 2016-03-06 17:16
That's not the problem.  I'm thinking --- you need to tell systemd to allow the service to start.
Try: `sudo systemctl enable tor.service`

**Comment by SecUpwN** [comment] 2016-03-06 17:25
Result:

```
Created symlink from /etc/systemd/system/multi-user.target.wants/tor.service to /usr/lib/systemd/system/tor.service.
```

But this is strange:

```
SecUpwN@GLaDOS:~> toriptables2.py
usage: toriptables2.py [-h] [-l] [-f]

Tor Iptables script for loading and unloading iptables rules

optional arguments:
  -h, --help   show this help message and exit
  -l, --load   This option will load tor iptables rules
  -f, --flush  This option flushes the iptables rules to default
```
```
SecUpwN@GLaDOS:~> toriptables2.py -l
[!] Run as super user: No such file or directory
```
```
SecUpwN@GLaDOS:~> sudo toriptables2.py -l
sudo: toriptables2.py: Command not found
```

**Comment by ruped24** [comment] 2016-03-06 17:44
```
SecUpwN@GLaDOS:~> sudo toriptables2.py -l
sudo: toriptables2.py: Command not found
```
`sudo python toriptables2.py -l`

**Comment by SecUpwN** [comment] 2016-03-06 17:48
```
SecUpwN@GLaDOS:~> sudo python toriptables2.py -l
root's password:
python: can't open file 'toriptables2.py': [Errno 2] No such file or directory
```

**Comment by ruped24** [comment] 2016-03-06 18:10
You need to be where the file exist.

**Comment by SecUpwN** [comment] 2016-03-06 20:12
>You need to be where the file exist.

Gosh, how could I forget that? Unfortunately, I still get `[!] Can't get public ip address!`. What to do now?

**Comment by ruped24** [comment] 2016-03-06 21:14
I'm running out of suggestions.  It looks to be the distro has did somethings different for the iso you sent me.  Spin-up the iso in a vm and try it and compare ...  Without having that distro to test it on, I'm only guessing ...

**Comment by SecUpwN** [comment] 2016-03-06 21:27
>I'm running out of suggestions. It looks to be the distro has did somethings different for the iso you sent me.

I begin to supsect the whole thing could be errors on my part. Could you maybe update your script so that it installs itself and sets the right permissions in the right places to verify it is indeed the distro failing?

**Comment by ruped24** [comment] 2016-03-06 21:43
`Could you maybe update your script` 

That will break it on kali linux (pentesting community). 
That was the target.  It works as intended on the target.

**Comment by SecUpwN** [comment] 2016-03-06 21:55
>That will break it on kali linux (pentesting community).
>That was the target. It works as intended on the target.

Fair. How to do a full stacktrace so that you can see the core error?

**Comment by ruped24** [comment] 2016-03-06 21:58
My conclustion:

It works with the change on Suse 13.
It works on Debian base distro.

I no idea how your environment is setup.
1.  Run a debian base distro in a vm
2. Run it on Suse 13 in a vm

I've reached the end of the road on this.  i'll be closing this issue.  It looks to be something in your setup.  I'm out of time on this.  Have to get back to work.

I hope you find a solution...

**Comment by ruped24** [comment] 2016-03-06 22:07
Only thing is left, is to give me access ;)
You that's not something you want to do.

**Comment by ruped24** [comment] 2016-03-06 22:23
Closed:
Bleeding edge distro.

**Closed by ruped24** 2016-03-06 22:23 UTC

**Comment by SecUpwN** [comment] 2016-03-08 14:01
@ruped24, thanks for everything you tried though. I'll keep testing your script and will notify once it's working and what I did to accomplish that. Please help adding https://github.com/micahflee/torbrowser-launcher/issues/223.
