### ISSUE TITLE
Scan results differ from proxychains

### ISSUE THREAD

**Issue by sssseossss** [ruped24/toriptables2#9] opened 2017-07-27 14:28 UTC
Hi Ruped!
thanks for quick response. I have an issue/observation:

> sudo ./toriptables2.py -l
>  [+] Anonymizer status [ON]
>  [*] Getting public IP, please wait...
>  [+] Your IP is 173.14.173.227
> m@user:~$ nmap -p 80,443,22 -PN -n -sT 51.XXX.XXX.XXX
> 
> Starting Nmap 7.01 ( https://nmap.org ) at 2017-07-27 15:22 IST
> Nmap scan report for 51.XXX.XXX.XXX.
> Host is up (0.00014s latency).
> PORT    STATE SERVICE
> 22/tcp  open  ssh
> 80/tcp  open  http
> 443/tcp open  https
> 
> 
But if:
> sudo ./toriptables2.py -f
> [!] Anonymizer status [OFF]
> @user:~$ proxychains nmap -p 80,443,22 -PN -n -sT 51.XXX.XXX.XXX
> ProxyChains-3.1 (http://proxychains.sf.net)
> 
> Starting Nmap 7.01 ( https://nmap.org ) at 2017-07-27 15:22 IST
> |S-chain|-<>-127.0.0.1:9050-<><>-51.XXX.XXX.XXX:22-<><>-OK
> |S-chain|-<>-127.0.0.1:9050-<><>-51.XXX.XXX.XXX:443-<--denied
> |S-chain|-<>-127.0.0.1:9050-<><>-51.XXX.XXX.XXX:80-<--timeout
> Nmap scan report for 51.XXX.XXX.XXX
> Host is up (0.44s latency).
> PORT    STATE  SERVICE
> 22/tcp  open   ssh
> 80/tcp  closed http
> 443/tcp closed https

can you suggest whats is the issue as I'm getting different results? Thanks!

**Comment by ruped24** [comment] 2017-07-27 14:33
Hello.

I can't offer support for other anonymizer.  Check with said tool's forum.
This is not a toriptable2 bug issue.

Closing

**Comment by sssseossss** [comment] 2017-07-27 14:35
You see, the idea is that whenever I use nmap with your given toriptables2.py I get all ports open, no matter what. Therefore I think it is to do with iptables.

**Comment by ruped24** [comment] 2017-07-27 14:37
This is not a bug issuse.

**Closed by ruped24** 2017-07-27 14:37 UTC
